I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/web.rpy", line 585, in <module>
  File "game/web.rpy", line 420, in build_web
PermissionError: [WinError 5] Отказано в доступе: 'C:\\Users\\MAMALUKS\\OneDrive\\Рабочий стол\\quest\\TravellinginRussia-1.0-dists\\TravellinginRussia-1.0-web\\icons'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "launcher/game/front_page.rpyc", line 246, in script call
  File "launcher/game/web.rpyc", line 585, in script
  File "C:\Users\MAMALUKS\OneDrive\Рабочий стол\Новая папка\renpy\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\MAMALUKS\OneDrive\Рабочий стол\Новая папка\renpy\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/web.rpy", line 585, in <module>
  File "game/web.rpy", line 420, in build_web
  File "lib/python3.9/shutil.py", line 749, in rmtree
  File "lib/python3.9/shutil.py", line 622, in _rmtree_unsafe
  File "lib/python3.9/shutil.py", line 631, in _rmtree_unsafe
  File "lib/python3.9/shutil.py", line 629, in _rmtree_unsafe
PermissionError: [WinError 5] Отказано в доступе: 'C:\\Users\\MAMALUKS\\OneDrive\\Рабочий стол\\quest\\TravellinginRussia-1.0-dists\\TravellinginRussia-1.0-web\\icons'

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Ren'Py Launcher 8.3.7.25031702
Thu Sep 11 18:09:01 2025
